### ISSUE TITLE
Error when installing - File contains no section headers

### ISSUE THREAD

**Issue by jeremiahbenes** [HoustonDad/ea-apache24-mod_cloudflare#1]
I get the following error when downloading and installing the module: 

> root@helios [~]# yum install ea-apache24-mod_cloudflare
> Loaded plugins: fastestmirror, rhnplugin, tsflags, universal-hooks
> Config Error: File contains no section headers.
> file: file:///etc/yum.repos.d/EA4-Mod-Cloudflare.repo, line: 1
> '\xed\xab\xee\xdb\x03\x00\x00\x00\x00\x01ea-apache24-mod_cloudflare-1.2.0-2.1\x0                                                                                                                                                                                               0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0                                                                                                                                                                                               0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x05\x00\x00\x00\x00\x00\x00\x0                                                                                                                                                                                               0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x8e\xad\xe8\x01\x00\x00\x00\x00\x00\x00\x0                                                                                                                                                                                               0\x07\x00\x00\x02\x84\x00\x00\x00>\x00\x00\x00\x07\x00\x00\x02t\x00\x00\x00\x10\                                                                                                                                                                                               x00\x00\x01\x0c\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x01\x18\x00\x00\x01\r\x0                                                                                                                                                                                               0\x00\x00\x06\x00\x00\x01\x18\x00\x00\x00\x01\x00\x00\x03\xe8\x00\x00\x00\x04\x0                                                                                                                                                                                               0\x00\x01D\x00\x00\x00\x01\x00\x00\x03\xea\x00\x00\x00\x07\x00\x00\x01H\x00\x00\                                                                                                                                                                                               x01\x18\x00\x00\x03\xec\x00\x00\x00\x07\x00\x00\x02`\x00\x00\x00\x10\x00\x00\x03                                                                                                                                                                                               \xef\x00\x00\x00\x04\x00\x00\x02p\x00\x00\x00\x01\x89\x01\x15\x03\x05\x00WR\x8c\                                                                                                                                                                                               x8b\xfb\x9cv\xba\xfc\xbf$5\x01\x08\xd6\x93\x08\x00\x96\x1c\xb8+.w_\xe7;\x89\xa8J                                                                                                                                                                                               \rc\x8f\xd8\x03\xd6\xaf\xea\xb9\x8f@p\xf7uB,\xd5\xc8%\xb6\xa1]\xce=<.\xd4L8$\x8d                                                                                                                                                                                               \xd9\xa0\x86\j\xb0\xd4\xf4\x87\xb3D\xaeO\xab\xe6P\xe9\xe2\x16K.\xdf\x06Q\xc5\x9                                                                                                                                                                                               bWhNg2V-\x7fiaF\x10\x98\x16\xa4\xf2 \xa2\x1a\x14\xd5\xf2\x96\x94\xa2\xe1\x95I\xf                                                                                                                                                                                               aH\x92)\x9b\xd6\x93\xe7\xe8\xd6\x9a\x07\x11Vu;\xf8\x1f\x9dkgx\xdc\xbfq\x99\xaf\x                                                                                                                                                                                               d5\xd2_\x90\xe7R\x07\x07\xfbJ\xa6Q\xdb\xb7\x02\x1f)\xe7\x9e2o\xa8\xce%\xef\xff+\                                                                                                                                                                                               xc7\x97\xe8\xfe\x03\xbf\x05\x10\x81\xd1[\x9a\xa9\xb6\x8bD\xe7\xc3"u\x85\xed\x858                                                                                                                                                                                               G$\xea\xd9\x06\xf0\xe2?\xec\xd87\xdb\xde\x99/\x9e0\x1fe;U\x1a\x04\x94-\xef\x81\x                                                                                                                                                                                               c9A\x87\xce.\xde\xee\xb3\x82kGp\x15\x9d\xcb\xf8\xb2\xaeL\xb9\xbd\x07+\x05*\x9a\x                                                                                                                                                                                               a8\xa9\xb9B\xae\xc8n\xd2\xc4:\x03\xfeoFd\xa6\xb0\xc2M\xbdv\xe0\xcc\x8eD\xb0\xc7\                                                                                                                                                                                               x98e6ff7bea46634786c9620a29226940114311a6de\x00\x00\x00\x00\x00\x00 \xc8\x89\x01                                                                                                                                                                                               \x15\x03\x05\x00WR\x8c\x8b\xfb\x9cv\xba\xfc\xbf$5\x01\x080\x9c\x08\x00\xb2\xf8F\                                                                                                                                                                                               x91\x84\x1f\x07\x10;\x8d]\xe7\xb0\xd64\xe9L\x01\xac\x98\xdf;\x1d\xfd\xe7\x14\xef                                                                                                                                                                                               \xbc\xca\x19\xbd\x94\xb2\xf9;\xcf\x97\x91\x99\xe9\xad\x0f\xb9\x06m\xc7\x8cYOc\x1                                                                                                                                                                                               5\x9a\xa6:\x992\x08\x1e\xf0e\x1c\xec\xa3\x1c:i\xb8\xd1\xc0\xd1.\x97o\xdd\r\x88G\                                                                                                                                                                                               xa7\xc4\x99\xec\x1bE8\x84\xc2\x08\xf0\x1c\n

What is going wrong? I'm running cPanel 56.0 (build 22) with CloudLinux.

**Comment by HoustonDad** [comment]
There looks to be something pretty nasty going on with your paste job into the .repo file. Can you copy and paste in the contents of '/etc/yum.repos.d/EA4-Mod-Cloudflare.repo'?  It should only contain the followinging (In this example, this is for CentOS 7)

`````` [home_Jperkster_EA4_Mod_Cloudflare]
name=home:Jperkster:EA4_Mod_Cloudflare (CentOS-7)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/home:/Jperkster:/EA4_Mod_Cloudflare/CentOS-7/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/home:/Jperkster:/EA4_Mod_Cloudflare/CentOS-7//repodata/repomd.xml.key
enabled=1```
``````

**Comment by HoustonDad** [comment]
I've updated the installation instructions a bit more in hopes this solves your issue. Download the .repo file again and you should be in business.
