### ISSUE TITLE
cPanel documentation link

### ISSUE THREAD

**Issue by tripflex** [HoustonDad/ea-apache24-mod_cloudflare#3]
Not sure if you were aware of this or not, but cPanel has this in their documentation now:
https://documentation.cpanel.net/display/CKB/Apache+Module%3A+CloudFlare

**Comment by HoustonDad** [comment]
Thanks! I talked to our documentation department on this. Initially it was in our EA4 documentation, and I didn't feel 100% comfortable with it there. So we moved it to the Knowledge Base.
