### ISSUE TITLE
Please explain these unknown IP blocks in CloudFlare config

### ISSUE THREAD

**Issue by tripflex** [HoustonDad/ea-apache24-mod_cloudflare#5]
Can you explain where these IP blocks are coming from?  CloudFlare says they're not theirs, and ARIN lookup shows that only one block _may_ have been a CloudFlare IP block, but CloudFlare confirmed neither of these are being used ....

`204.93.240.0/24 204.93.177.0/24`

https://github.com/JPerkster/ea-apache24-mod_cloudflare/blob/EA4_Mod_Cloudflare/SOURCES/cloudflare.conf#L5

![](https://smyl.es/img/Screenshot_2016-09-15_05-39-26_PM.png)

**Comment by HoustonDad** [comment]
They are probably just old IPs. I'll remove them in the next update.

**Comment by HoustonDad** [comment]
I've removed these in 7393f148742491b1d1a0fc5d5ea7c0098c0fd304
