### ISSUE TITLE
Updated IP address ranges

### ISSUE THREAD

**Issue by peterglock** [HoustonDad/ea-apache24-mod_cloudflare#7]
According to Cloudflare they will be broadcasting from new IPs. Please update the address list to reflect IPv4 and IPv6 addresses here:

https://www.cloudflare.com/ips

**Comment by HoustonDad** [comment]
I've updated cloudflare.conf with the new IPv4 addresses, and I've added in the IPv6 addresses, in commit 47bb1da10b812254d57ad18de0789117930cd649
